name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Build for Cloudflare Workers
        run: npm run deploy:build

      - name: Verify build artifacts
        run: |
          echo "Checking Next.js build output..."
          ls -la .next/ || echo "❌ .next directory missing"
          echo "Checking OpenNext build output..."
          ls -la .open-next/
          test -f .open-next/worker.js && echo "✅ worker.js found" || echo "❌ worker.js missing"

      - name: Deploy to Cloudflare Workers
        run: npm run deploy:only
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Display deployment URL
        if: success()
        run: echo "✅ Successfully deployed to production!"
